name: programacion-cientifica
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=24.0
  - python=3.12
  - pip:
      - black==24.4.2
      - coloredlogs==15.0.1
      - mathplotlib==3.8.4
      - pandas==2.2.2
      - python-dotenv==1.0.1
